In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('dataanime.csv')
data

,Title,Type,Episodes,Status,Start airing,End airing,Starting season,Broadcast time,Producers,Licensors,Studios,Sources,Genres,Duration,Rating,Score,Scored by,Members,Favorites,Description
0,Fullmetal Alchemist: Brotherhood,TV,64,Finished Airing,2009-4-5,2010-7-4,Spring,Sundays at 17:00 (JST),"Aniplex,Square Enix,Mainichi Broadcasting Syst...","Funimation,Aniplex of America",Bones,Manga,"Action,Military,Adventure,Comedy,Drama,Magic,F...",24 min. per ep.,R,9.25,719706,1176368,105387,"""In order for something to be obtained, someth..."
1,Kimi no Na wa.,Movie,1,Finished Airing,2016-8-26,-,-,-,"Kadokawa Shoten,Toho,Sound Team Don Juan,Lawso...","Funimation,NYAV Post",CoMix Wave Films,Original,"Supernatural,Drama,Romance,School",1 hr. 46 min.,PG-13,9.19,454969,705186,33936,"Mitsuha Miyamizu, a high school girl, yearns t..."
2,Gintama°,TV,51,Finished Airing,2015-4-8,2016-3-30,Spring,Wednesdays at 18:00 (JST),"TV Tokyo,Aniplex,Dentsu","Funimation,Crunchyroll",Bandai Namco Pictures,Manga,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",24 min. per ep.,R,9.16,70279,194359,5597,"Gintoki, Shinpachi, and Kagura return as the f..."
3,Steins;Gate 0,TV,23,Currently Airing,2018-4-12,-,Spring,Thursdays at 01:35 (JST),Nitroplus,Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",23 min. per ep.,PG-13,9.16,12609,186331,1117,The dark untold story of Steins;Gate that lead...
4,Steins;Gate,TV,24,Finished Airing,2011-4-6,2011-9-14,Spring,Wednesdays at 02:05 (JST),"Frontier Works,Media Factory,Movic,AT-X,Kadoka...",Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",24 min. per ep.,PG-13,9.14,552791,990419,90365,The self-proclaimed mad scientist Rintarou Oka...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,Kuroshitsuji II,TV,12,Finished Airing,2010-7-2,2010-9-17,Summer,-,"Aniplex,Square Enix,Mainichi Broadcasting System",Funimation,A-1 Pictures,Manga,"Action,Comedy,Demons,Supernatural,Fantasy,Shounen",24 min. per ep.,R,7.48,171506,296985,3576,The stage of Kuroshitsuji II opens on the life...
1559,Minami-ke Natsuyasumi,OVA,1,Finished Airing,2013-8-6,-,-,-,Starchild Records,-,feel.,Manga,"Comedy,Slice of Life",28 min.,PG-13,7.48,6062,12111,4,Second Minami-ke OVA bundled with the 11th vol...
1560,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,Movie,1,Finished Airing,2009-8-1,-,-,-,Toho,Viz Media,Studio Pierrot,Manga,"Action,Comedy,Martial Arts,Shounen,Super Power",1 hr. 35 min.,PG-13,7.48,61505,104288,129,Ninjas with bloodline limits begin disappearin...
1561,Persona 4 the Animation: The Factor of Hope,Movie,1,Finished Airing,2012-6-9,-,-,-,Index,-,AIC A.S.T.A.,-,"Adventure,Mystery,Super Power,Supernatural,School",1 hr. 30 min.,PG-13,7.48,3054,12868,12,Recap of the entire 25-episode television anim...
1562,Re:␣Hamatora,TV,12,Finished Airing,2014-7-8,2014-9-23,Summer,Tuesdays at 02:05 (JST),"TV Tokyo,Sotsu,AT-X,DAX Production,NAZ,DIVE II...",Sentai Filmworks,Lerche,Original,"Mystery,Comedy,Super Power,Drama",24 min. per ep.,R,7.48,46334,99299,330,It has been three months since the incident at...

Display the head of our Data

In [5]:
data.head()

,Title,Type,Episodes,Status,Start airing,End airing,Starting season,Broadcast time,Producers,Licensors,Studios,Sources,Genres,Duration,Rating,Score,Scored by,Members,Favorites,Description
0,Fullmetal Alchemist: Brotherhood,TV,64,Finished Airing,2009-4-5,2010-7-4,Spring,Sundays at 17:00 (JST),"Aniplex,Square Enix,Mainichi Broadcasting Syst...","Funimation,Aniplex of America",Bones,Manga,"Action,Military,Adventure,Comedy,Drama,Magic,F...",24 min. per ep.,R,9.25,719706,1176368,105387,"""In order for something to be obtained, someth..."
1,Kimi no Na wa.,Movie,1,Finished Airing,2016-8-26,-,-,-,"Kadokawa Shoten,Toho,Sound Team Don Juan,Lawso...","Funimation,NYAV Post",CoMix Wave Films,Original,"Supernatural,Drama,Romance,School",1 hr. 46 min.,PG-13,9.19,454969,705186,33936,"Mitsuha Miyamizu, a high school girl, yearns t..."
2,Gintama°,TV,51,Finished Airing,2015-4-8,2016-3-30,Spring,Wednesdays at 18:00 (JST),"TV Tokyo,Aniplex,Dentsu","Funimation,Crunchyroll",Bandai Namco Pictures,Manga,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",24 min. per ep.,R,9.16,70279,194359,5597,"Gintoki, Shinpachi, and Kagura return as the f..."
3,Steins;Gate 0,TV,23,Currently Airing,2018-4-12,-,Spring,Thursdays at 01:35 (JST),Nitroplus,Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",23 min. per ep.,PG-13,9.16,12609,186331,1117,The dark untold story of Steins;Gate that lead...
4,Steins;Gate,TV,24,Finished Airing,2011-4-6,2011-9-14,Spring,Wednesdays at 02:05 (JST),"Frontier Works,Media Factory,Movic,AT-X,Kadoka...",Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",24 min. per ep.,PG-13,9.14,552791,990419,90365,The self-proclaimed mad scientist Rintarou Oka...

Display the Tail of out Data

In [6]:
data.tail()

,Title,Type,Episodes,Status,Start airing,End airing,Starting season,Broadcast time,Producers,Licensors,Studios,Sources,Genres,Duration,Rating,Score,Scored by,Members,Favorites,Description
1558,Kuroshitsuji II,TV,12,Finished Airing,2010-7-2,2010-9-17,Summer,-,"Aniplex,Square Enix,Mainichi Broadcasting System",Funimation,A-1 Pictures,Manga,"Action,Comedy,Demons,Supernatural,Fantasy,Shounen",24 min. per ep.,R,7.48,171506,296985,3576,The stage of Kuroshitsuji II opens on the life...
1559,Minami-ke Natsuyasumi,OVA,1,Finished Airing,2013-8-6,-,-,-,Starchild Records,-,feel.,Manga,"Comedy,Slice of Life",28 min.,PG-13,7.48,6062,12111,4,Second Minami-ke OVA bundled with the 11th vol...
1560,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,Movie,1,Finished Airing,2009-8-1,-,-,-,Toho,Viz Media,Studio Pierrot,Manga,"Action,Comedy,Martial Arts,Shounen,Super Power",1 hr. 35 min.,PG-13,7.48,61505,104288,129,Ninjas with bloodline limits begin disappearin...
1561,Persona 4 the Animation: The Factor of Hope,Movie,1,Finished Airing,2012-6-9,-,-,-,Index,-,AIC A.S.T.A.,-,"Adventure,Mystery,Super Power,Supernatural,School",1 hr. 30 min.,PG-13,7.48,3054,12868,12,Recap of the entire 25-episode television anim...
1562,Re:␣Hamatora,TV,12,Finished Airing,2014-7-8,2014-9-23,Summer,Tuesdays at 02:05 (JST),"TV Tokyo,Sotsu,AT-X,DAX Production,NAZ,DIVE II...",Sentai Filmworks,Lerche,Original,"Mystery,Comedy,Super Power,Drama",24 min. per ep.,R,7.48,46334,99299,330,It has been three months since the incident at...

Display the top 5 Row of out Data

In [7]:
data.head(5)

,Title,Type,Episodes,Status,Start airing,End airing,Starting season,Broadcast time,Producers,Licensors,Studios,Sources,Genres,Duration,Rating,Score,Scored by,Members,Favorites,Description
0,Fullmetal Alchemist: Brotherhood,TV,64,Finished Airing,2009-4-5,2010-7-4,Spring,Sundays at 17:00 (JST),"Aniplex,Square Enix,Mainichi Broadcasting Syst...","Funimation,Aniplex of America",Bones,Manga,"Action,Military,Adventure,Comedy,Drama,Magic,F...",24 min. per ep.,R,9.25,719706,1176368,105387,"""In order for something to be obtained, someth..."
1,Kimi no Na wa.,Movie,1,Finished Airing,2016-8-26,-,-,-,"Kadokawa Shoten,Toho,Sound Team Don Juan,Lawso...","Funimation,NYAV Post",CoMix Wave Films,Original,"Supernatural,Drama,Romance,School",1 hr. 46 min.,PG-13,9.19,454969,705186,33936,"Mitsuha Miyamizu, a high school girl, yearns t..."
2,Gintama°,TV,51,Finished Airing,2015-4-8,2016-3-30,Spring,Wednesdays at 18:00 (JST),"TV Tokyo,Aniplex,Dentsu","Funimation,Crunchyroll",Bandai Namco Pictures,Manga,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",24 min. per ep.,R,9.16,70279,194359,5597,"Gintoki, Shinpachi, and Kagura return as the f..."
3,Steins;Gate 0,TV,23,Currently Airing,2018-4-12,-,Spring,Thursdays at 01:35 (JST),Nitroplus,Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",23 min. per ep.,PG-13,9.16,12609,186331,1117,The dark untold story of Steins;Gate that lead...
4,Steins;Gate,TV,24,Finished Airing,2011-4-6,2011-9-14,Spring,Wednesdays at 02:05 (JST),"Frontier Works,Media Factory,Movic,AT-X,Kadoka...",Funimation,White Fox,Visual novel,"Sci-Fi,Thriller",24 min. per ep.,PG-13,9.14,552791,990419,90365,The self-proclaimed mad scientist Rintarou Oka...

Display the bottom 5 row of out Data

In [8]:
data.tail(5)

,Title,Type,Episodes,Status,Start airing,End airing,Starting season,Broadcast time,Producers,Licensors,Studios,Sources,Genres,Duration,Rating,Score,Scored by,Members,Favorites,Description
1558,Kuroshitsuji II,TV,12,Finished Airing,2010-7-2,2010-9-17,Summer,-,"Aniplex,Square Enix,Mainichi Broadcasting System",Funimation,A-1 Pictures,Manga,"Action,Comedy,Demons,Supernatural,Fantasy,Shounen",24 min. per ep.,R,7.48,171506,296985,3576,The stage of Kuroshitsuji II opens on the life...
1559,Minami-ke Natsuyasumi,OVA,1,Finished Airing,2013-8-6,-,-,-,Starchild Records,-,feel.,Manga,"Comedy,Slice of Life",28 min.,PG-13,7.48,6062,12111,4,Second Minami-ke OVA bundled with the 11th vol...
1560,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,Movie,1,Finished Airing,2009-8-1,-,-,-,Toho,Viz Media,Studio Pierrot,Manga,"Action,Comedy,Martial Arts,Shounen,Super Power",1 hr. 35 min.,PG-13,7.48,61505,104288,129,Ninjas with bloodline limits begin disappearin...
1561,Persona 4 the Animation: The Factor of Hope,Movie,1,Finished Airing,2012-6-9,-,-,-,Index,-,AIC A.S.T.A.,-,"Adventure,Mystery,Super Power,Supernatural,School",1 hr. 30 min.,PG-13,7.48,3054,12868,12,Recap of the entire 25-episode television anim...
1562,Re:␣Hamatora,TV,12,Finished Airing,2014-7-8,2014-9-23,Summer,Tuesdays at 02:05 (JST),"TV Tokyo,Sotsu,AT-X,DAX Production,NAZ,DIVE II...",Sentai Filmworks,Lerche,Original,"Mystery,Comedy,Super Power,Drama",24 min. per ep.,R,7.48,46334,99299,330,It has been three months since the incident at...

Get the row of out data by its index number

In [9]:
data.loc[1]

Title                                                 Kimi no Na wa.
Type                                                           Movie
Episodes                                                           1
Status                                               Finished Airing
Start airing                                               2016-8-26
End airing                                                         -
Starting season                                                    -
Broadcast time                                                     -
Producers          Kadokawa Shoten,Toho,Sound Team Don Juan,Lawso...
Licensors                                       Funimation,NYAV Post
Studios                                             CoMix Wave Films
Sources                                                     Original
Genres                             Supernatural,Drama,Romance,School
Duration                                               1 hr. 46 min.
Rating                                                         PG-13
Score                                                           9.19
Scored by                                                     454969
Members                                                       705186
Favorites                                                      33936
Description        Mitsuha Miyamizu, a high school girl, yearns t...
Name: 1, dtype: object

In [10]:
data.loc[2]

Title                                                       Gintama°
Type                                                              TV
Episodes                                                          51
Status                                               Finished Airing
Start airing                                                2015-4-8
End airing                                                 2016-3-30
Starting season                                               Spring
Broadcast time                             Wednesdays at 18:00 (JST)
Producers                                    TV Tokyo,Aniplex,Dentsu
Licensors                                     Funimation,Crunchyroll
Studios                                        Bandai Namco Pictures
Sources                                                        Manga
Genres             Action,Comedy,Historical,Parody,Samurai,Sci-Fi...
Duration                                             24 min. per ep.
Rating                                                             R
Score                                                           9.16
Scored by                                                      70279
Members                                                       194359
Favorites                                                       5597
Description        Gintoki, Shinpachi, and Kagura return as the f...
Name: 2, dtype: object

In [11]:
data.loc[6]

Title                                                       Gintama'
Type                                                              TV
Episodes                                                          51
Status                                               Finished Airing
Start airing                                                2011-4-4
End airing                                                 2012-3-26
Starting season                                               Spring
Broadcast time                                Mondays at 18:00 (JST)
Producers          TV Tokyo,Aniplex,Dentsu,Trinity Sound,Miracle ...
Licensors                                                          -
Studios                                                      Sunrise
Sources                                                        Manga
Genres             Action,Sci-Fi,Comedy,Historical,Parody,Samurai...
Duration                                             24 min. per ep.
Rating                                                         PG-13
Score                                                           9.11
Scored by                                                      90758
Members                                                       212238
Favorites                                                       4533
Description        After a one-year hiatus, Shinpachi Shimura ret...
Name: 6, dtype: object

Get a specific Column

In [12]:
data.loc[1,'Type']

'Movie'

Another way

In [14]:
data.loc[6]['Members']

np.int64(212238)

In [15]:
data.shape

(1563, 20)

In [16]:
data.size

31260

In [17]:
data.Type

0          TV
1       Movie
2          TV
3          TV
4          TV
        ...
1558       TV
1559      OVA
1560    Movie
1561    Movie
1562       TV
Name: Type, Length: 1563, dtype: str

In [21]:
data.dtypes

Title                  str
Type                   str
Episodes               str
Status                 str
Start airing           str
End airing             str
Starting season        str
Broadcast time         str
Producers              str
Licensors              str
Studios                str
Sources                str
Genres                 str
Duration               str
Rating                 str
Score              float64
Scored by            int64
Members              int64
Favorites            int64
Description            str
dtype: object

In [28]:
data['Episodes'].head()

0    64
1     1
2    51
3    23
4    24
Name: Episodes, dtype: str

In [ ]:
data['Episodes'] = pd.to_numeric(data['Episodes'])

KeyError: 'Episodes    '