# Pandas Series
A Pandas Series is a one-dimensional labeled array capable of holding data of any type (integers, strings, floating-point numbers, Python objects, etc.). You can think of it as a single column in an Excel spreadsheet or a database table, where each value is paired with a specific row label called an index

# Creating  Series
There are multiple ways to create a pandas Series:

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

automatically label set in the dictionary

In [5]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# Data Frame

In [6]:
data = {
    'Name': ["Sakshi","Madhav","Adarsh","Pannu"],
    "Age" : [28, 34, 29, 42],
    "City": ['Lucknow','Mathura','Ayodhya','Noida'],
    "Salary":[100000, 98000,99000,960000]
}

In [7]:
df = pd.DataFrame(data)

In [8]:
data_list = [
    ['John',23 ,'America', 39000],
    ['Linda',34,'canada',239000],
    ['Peter',22,'Newyork',30000],
    ['Lucy',29,'Paris',2333000]
]

In [9]:
pd.DataFrame(data_list)

       0   1        2        3
0   John  23  America    39000
1  Linda  34   canada   239000
2  Peter  22  Newyork    30000
3   Lucy  29    Paris  2333000

In [10]:
data_list = [
    ['John',23 ,'America', 39000],
    ['Linda',34,'canada',239000],
    ['Peter',22,'Newyork',30000],
    ['Lucy',29,'Paris',2333000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age     City   Salary
0   John   23  America    39000
1  Linda   34   canada   239000
2  Peter   22  Newyork    30000
3   Lucy   29    Paris  2333000

In [11]:
df2["Designation"] =["Doctor","Engg","Doctor","Engg"]
df2

    Name  Age     City   Salary Designation
0   John   23  America    39000      Doctor
1  Linda   34   canada   239000        Engg
2  Peter   22  Newyork    30000      Doctor
3   Lucy   29    Paris  2333000        Engg

Removing Columns

In [12]:
df2

    Name  Age     City   Salary Designation
0   John   23  America    39000      Doctor
1  Linda   34   canada   239000        Engg
2  Peter   22  Newyork    30000      Doctor
3   Lucy   29    Paris  2333000        Engg

In [13]:
df2[["Name","City"]]

    Name     City
0   John  America
1  Linda   canada
2  Peter  Newyork
3   Lucy    Paris

In [14]:
df2["Designation"] = ["Doctor", "Engineer","Pilot","Airhostes"]
df2

    Name  Age     City   Salary Designation
0   John   23  America    39000      Doctor
1  Linda   34   canada   239000    Engineer
2  Peter   22  Newyork    30000       Pilot
3   Lucy   29    Paris  2333000   Airhostes

In [15]:
df2

    Name  Age     City   Salary Designation
0   John   23  America    39000      Doctor
1  Linda   34   canada   239000    Engineer
2  Peter   22  Newyork    30000       Pilot
3   Lucy   29    Paris  2333000   Airhostes

In [16]:
df2.drop('City', axis = 1, inplace = True)
df2

    Name  Age   Salary Designation
0   John   23    39000      Doctor
1  Linda   34   239000    Engineer
2  Peter   22    30000       Pilot
3   Lucy   29  2333000   Airhostes

# Selecting Rows

In [17]:
df2

    Name  Age   Salary Designation
0   John   23    39000      Doctor
1  Linda   34   239000    Engineer
2  Peter   22    30000       Pilot
3   Lucy   29  2333000   Airhostes

In [18]:
df2.loc[[0,1]]

    Name  Age  Salary Designation
0   John   23   39000      Doctor
1  Linda   34  239000    Engineer

In [19]:
df2.iloc[3]

Name                Lucy
Age                   29
Salary           2333000
Designation    Airhostes
Name: 3, dtype: object

## Selecting Subsets of Rows and Columns

In [20]:
data_list = [
    ['John',23 ,'America', 39000],
    ['Linda',34,'Paris',239000],
    ['Peter',22,'Newyork',30000],
    ['Lucy',29,'canada',2333000]
]
df = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df = pd.DataFrame(data_list,columns = columns)
df

    Name  Age     City   Salary
0   John   23  America    39000
1  Linda   34    Paris   239000
2  Peter   22  Newyork    30000
3   Lucy   29   canada  2333000

In [21]:
df.loc[[0,1]]

    Name  Age     City  Salary
0   John   23  America   39000
1  Linda   34    Paris  239000

In [22]:
df.loc[[0,1]] [['Age','Salary']]

   Age  Salary
0   23   39000
1   34  239000

# Conditional Selection

In [23]:
# I only want to see those people whose age is above 30

df[df["Age"] > 30]

    Name  Age   City  Salary
1  Linda   34  Paris  239000

In [24]:
# only want people whose age is above 30 and their city must be paris
df[(df["Age"] > 30 )& (df["City"] == 'Paris')]

    Name  Age   City  Salary
1  Linda   34  Paris  239000

## Missing Data

Finding Missing Data

In [25]:
data = {
    'A': [1,2, np.nan, 4,5],
    'B': [1,2,3,4,5 ],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5],
    'E':[1,2,3,4,5]
}
df_find_m =pd.DataFrame(data)
df_find_m

     A  B    C    D  E
0  1.0  1  1.0  1.0  1
1  2.0  2  2.0  NaN  2
2  NaN  3  3.0  NaN  3
3  4.0  4  NaN  NaN  4
4  5.0  5  NaN  5.0  5

In [26]:
df_find_m.isna()

       A      B      C      D      E
0  False  False  False  False  False
1  False  False  False   True  False
2   True  False  False   True  False
3  False  False   True   True  False
4  False  False   True  False  False

In [27]:
df_find_m.isna().sum()

A    1
B    0
C    2
D    3
E    0
dtype: int64

In [28]:
df_find_m.isna().any()

A     True
B    False
C     True
D     True
E    False
dtype: bool

Removing the Missing Data

In [29]:
df_find_m.dropna()

     A  B    C    D  E
0  1.0  1  1.0  1.0  1

In [30]:
df_find_m.dropna(thresh = 4)

     A  B    C    D  E
0  1.0  1  1.0  1.0  1
1  2.0  2  2.0  NaN  2
4  5.0  5  NaN  5.0  5

Filling the missing value

In [31]:
df_find_m

     A  B    C    D  E
0  1.0  1  1.0  1.0  1
1  2.0  2  2.0  NaN  2
2  NaN  3  3.0  NaN  3
3  4.0  4  NaN  NaN  4
4  5.0  5  NaN  5.0  5

In [32]:
df_find_m.fillna(0)

     A  B    C    D  E
0  1.0  1  1.0  1.0  1
1  2.0  2  2.0  0.0  2
2  0.0  3  3.0  0.0  3
3  4.0  4  0.0  0.0  4
4  5.0  5  0.0  5.0  5

In [33]:
values = {"A":0,"B":100,"C":300,"D":400,"E":500}
df_find_m.fillna(value=values)

     A  B      C      D  E
0  1.0  1    1.0    1.0  1
1  2.0  2    2.0  400.0  2
2  0.0  3    3.0  400.0  3
3  4.0  4  300.0  400.0  4
4  5.0  5  300.0    5.0  5

In [34]:
df_find_m.fillna(df_find_m.mean())

     A  B    C    D  E
0  1.0  1  1.0  1.0  1
1  2.0  2  2.0  3.0  2
2  3.0  3  3.0  3.0  3
3  4.0  4  2.0  3.0  4
4  5.0  5  2.0  5.0  5

# Merging Joining Concatenation of 2 DataFrame Joining of 2 DataFrames

Merging to dataframes

In [35]:
# DataFrame 1 : employees 
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Anna','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','AI']
})
# DataFrame 2: salaries
salaries = pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[60000,80000,65000,70000,90000],
    'bonus':[5000,10000,7000,8000,12000]

})

In [36]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         AI

In [37]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [38]:
pd.merge(employees,salaries )

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [39]:
pd.merge(employees,salaries, on = 'employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [40]:
pd.merge(employees,salaries,on = 'employee_id',how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         AI      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [41]:
pd.merge(employees,salaries,on='employee_id',how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         AI      NaN      NaN

In [42]:
pd.merge(employees,salaries,on = 'employee_id',how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

concatenation of two DataFrame

In [43]:
data_1 = pd.DataFrame({
    "A":['A0',"A1",'A2'],
    "B":['B0','B1','B2'],
    "C":['C0','C1','C2']
})
data_2 = pd.DataFrame({
    "A":['A3','A4','A5'],
    "B":['B3','B4',"B5"],
    "C":['C3',"C4","C5"]
})

In [44]:
data_1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [45]:
data_2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [46]:
pd.concat([data_1,data_2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [47]:
pd.concat([data_1,data_2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining two DataFrame

In [48]:
data_f_1 = pd.DataFrame({
    'name': ['Alice','Bob','Charlie']
}, index = [1,2,3])
data_f_2 = pd.DataFrame({
    'score': [85,90,75]
}, index = [2,3,4])

In [49]:
data_f_1

      name
1    Alice
2      Bob
3  Charlie

In [50]:
data_f_2

   score
2     85
3     90
4     75

In [51]:
data_f_1.join(data_f_2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [52]:
data_f_1.join(data_f_2,how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [53]:
data = {
    'Category':['A','B','A','B','A','B','A','B'],
    'Store': ['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2025-10-01',periods=8)
}
data = pd.DataFrame(data)
data

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2025-10-01
1        B    S1    200        15 2025-10-02
2        A    S2    150        12 2025-10-03
3        B    S2    250        18 2025-10-04
4        A    S1    120         8 2025-10-05
5        B    S2    180        20 2025-10-06
6        A    S2    200        15 2025-10-07
7        B    S1    300        25 2025-10-08

In [54]:
# Group by Category and calculate the sum of Sales
data.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [55]:
data.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [56]:
data.groupby('Quantity')['Sales'].sum()

Quantity
8     120
10    100
12    150
15    400
18    250
20    180
25    300
Name: Sales, dtype: int64

In [57]:
data.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [58]:
data['Sales'].mean()

np.float64(187.5)

In [59]:
data['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [60]:
data['Sales'].max()

np.int64(300)

In [61]:
data['Sales'].min()

np.int64(100)

In [62]:
data['Sales'].median()

np.float64(190.0)

In [63]:
data['Sales'].count()

np.int64(8)

In [64]:
# mean median max min count std sum
data['Sales'].agg(["mean",'min','max','sum','std','median', 'count'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
std         66.062741
median     190.000000
count        8.000000
Name: Sales, dtype: float64

In [65]:
data['Sales'].agg('mode')

0    200
Name: Sales, dtype: int64

In [73]:
data = {
    'Date': pd.date_range('2023-01-01',periods = 20),
    'Product':['A','B','C','D'] * 5,
    'Region':['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep': ['John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
}
data = pd.DataFrame(data)
data['Month']=data['Date'].dt.month_name()
data['Quarter']= 'Q' + data['Date'].dt.quarter.astype(str)

data

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    891     16   John  January      Q1
1  2023-01-02       B   West    956     48   Mary  January      Q1
2  2023-01-03       C  North    717     85    Bob  January      Q1
3  2023-01-04       D  South    372     58  Alice  January      Q1
4  2023-01-05       A   East    705     51   John  January      Q1
5  2023-01-06       B   West    675     18   Mary  January      Q1
6  2023-01-07       C  North    657     38    Bob  January      Q1
7  2023-01-08       D  South    710     32  Alice  January      Q1
8  2023-01-09       A   East    771     28   John  January      Q1
9  2023-01-10       B   West    577     61   Mary  January      Q1
10 2023-01-11       C  North    563     96    Bob  January      Q1
11 2023-01-12       D  South    982     37  Alice  January      Q1
12 2023-01-13       A   East    957     95   John  January      Q1
13 2023-01-14       B   West    107     55   Mary  January      Q1
14 2023-01-15       C  North    775     32    Bob  January      Q1
15 2023-01-16       D  South    527     22  Alice  January      Q1
16 2023-01-17       A   East    605     15   John  January      Q1
17 2023-01-18       B   West    351     81   Mary  January      Q1
18 2023-01-19       C  North    661     72    Bob  January      Q1
19 2023-01-20       D  South    758     30  Alice  January      Q1

In [67]:
pd.pivot_table(data,values = 'Sales', index = 'Region', columns = 'Product',aggfunc = 'median')

Product      A      B      C      D
Region
East     280.0    NaN    NaN    NaN
North      NaN    NaN  537.0    NaN
South      NaN    NaN    NaN  616.0
West       NaN  736.0    NaN    NaN

In [74]:
pivot2 = pd.pivot_table(data, values=['Sales','Units'], index = 'Region',columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     785.8    NaN    NaN    NaN  41.0   NaN   NaN   NaN
North      NaN    NaN  674.6    NaN   NaN   NaN  64.6   NaN
South      NaN    NaN    NaN  669.8   NaN   NaN   NaN  35.8
West       NaN  533.2    NaN    NaN   NaN  52.6   NaN   NaN

Cross Tabs

cross tabs are mainly use for counting

In [76]:
pd.crosstab(data['Region'],data['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

DataFrames Basics Operations

In [78]:
df1 = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [10,20,30,40,50],
    'C': [100,200,300,400,500]

})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [79]:
df1.shape

(5, 3)

In [80]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [81]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [82]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [84]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

DataFrames Applying Functions

In [85]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [86]:
def square(x):
    return x **2

In [89]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [90]:
df1['A'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [91]:
df1['C'].apply(square)

0     10000
1     40000
2     90000
3    160000
4    250000
Name: C, dtype: int64

In [93]:
df1['B'] = df1['B'].apply(square)
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [95]:
df1['D'] = df1['B'].apply(square)
df1

   A        B    C               D
0  1    10000  100       100000000
1  2   160000  200     25600000000
2  3   810000  300    656100000000
3  4  2560000  400   6553600000000
4  5  6250000  500  39062500000000

By using lambda

In [98]:
df1['D'] = df1['B'].apply(lambda x : x**2)

In [99]:
df1

   A        B    C               D
0  1    10000  100       100000000
1  2   160000  200     25600000000
2  3   810000  300    656100000000
3  4  2560000  400   6553600000000
4  5  6250000  500  39062500000000